sudo: required

dist: trusty

language: python

python:
  - '2.7'

node_js:
  - '6'

cache:
  directories:
    - "~/.platformio"

install:
  - npm install
  - pip install -U platformio

jobs:
  include:
  - stage: test
    script: script/cibuild
  - stage: deploy
    if: type IN (pull_request)
    script: script/deploy
