sudo: required

dist: trusty

language: python

python:
  - '2.7'

node_js:
  - '6'

env:
  global:
  - secure: NCRL3Xp/yy3UQkY4KedQKlXZJcChkTsQx3Yc3jeOKiYVLgrLxSAeZ7lSUSgRe+b7jSm262FYFDl98MgwHqYGXNEn5daz5fX61nfRApmmNMoxGD57EO8pQADOTn8x7x0jypsyK+CyhS3ve4TtD3TFKFqEmMffwk0TVVcTfnSLAciRfCR4TCNUnouwoAsyD2sSN+tT9v/Xpo4yT5klU0hq7E9nswIoSSe8bo9k24epINiLYUPObBGwgwVbye8g4uH8eZWI+m0Tf1hqS8IKvvcLG71kDenurjjmu+ejCV+OIj3xLCoviCJYU2DasE1Aeg6sATXjwXYYVYLAfvYJDT4KHKUxYdDV+5eswlCYLmeo68hkdszfxcEyNpD0eWhzwrG0A0uiTuRVxQiLAEMUAXlHBt4+vLa9Y5YAhmts02cZP2xIY85QSTH5/245oCI5mY5l2FcBxqfJ7Yab4RVlbYmZUsoUEijhsBuM5rZfXsZ2qTUnsbOqII5zYunFXUWHwOKs6u7sURsr3BEznqaBIF79Dtox6YVXttpQ8QuxB2bnmsRH5/li0FozbngZ4unf8B57SQO0xoMlRXodD9itHCOnXf082pslRufnP6A0EL6bES6QmfqBP9n7rFD4H5RuL2ZcGJKEqrY28TGdKTCksCaQVSHm5yqOl6UAnH762TH3NKo=
  - secure: UM+9q76oy09fAVhT827+hzMhZsGIHPUTm3INpJra9cfLsp51ZntpA7BO5wa+1xH+rEM8E9dyQevLftQmDbOGAd+YYHmg85ZVyyEbP9d3BsY3K+K00kLHkw94a0QOEcoQzATmbD/1IaBtSfGKfNqpZaA+NHxJWZHVPULyyIlyL8VqfhYnP56c1yoi50e8DrCUHHbHMaSIBZE537ed39WiOtOuoAruGC1uTJPoM6N/BulgGrn5d+Krrhk2iEyaoJm1UcK47XFIyJp9bhLwFPU5bXkpV14MDDjGXXC3ZJEZmq+9vuHKdpaNm0+KqQVFv1sZFLyIuyfOS56fWzwGASMPRSaBulNhE8C8QG25Wq0TwhOPe2rT9282NxMeqnz9FN351sxidsyyL0Pk6ckJD/iJ7AoSZHoXyykp0UvMe9Ep2OI+tdw7YAFp83Bevi2KGku+SaCGUd6Sy7k/4qh389e5LlH5WSgXk1xk+ysnZbXTzHStWt88hq3xWsbmOJhAa2GI6u0Q2+jSfpUDBAqSlEhXneOc+CzDNHPHVXdZUYDQtRy4wIaieJK9cPnNHtHskhCD4Ek2xp4rPVhV0rn61joqosbNKw/nk2mcz2dskuI1x9swDf6F8vhf3itgIgJ8aDqdHfYyIIptAIgrnZjPOysG6aAKiGo4usA164sB00cosgU=
  - secure: CHTAO8kQN4kFyKHySBKiI4Ym6RKtVXVcQeS4RqtVgrpT9oKAEQMkkweyZV/YRQ1WAiACJDmM5Atv1TdmF/GeNxASDVFYxHGhrapIn8PKSOMWiAt3vJk3gDCWfaraZS101IXEBE5Y4YnyaIT66t+aXU6jT+pUq1B0opUWW4xF34EkJj25Z/IS9vjP8I5KQztqEigdY9BqDb9+i+7n3Mfe1xOP3Gv7qyZr1S6d/1wqFNXcyv1IAhI/ZNYMAXHFk+nXfit9DW+ltdba4IvtBHMrRVuDzANSXuW02uFJhC4GU0tyyIhU/sMeG/eL/9RqT2wGolgVpdu7ROHfK42ZCu8UuHx9K0JqNWefYh6ydse2T9ThHRKmL9WEuzD8PcxIJ79ISYko11OuEosPgnf5EFf2gY6o0/hXqGjXmqNv2+a+ryhGAepctIWE+PC1ytT0iVQl1BXWdrLgD1jXgVPa2SVFuXAYIAPJkeqTaSSe1f3cA24CpeuGhFBzZVkifKCD+rwM8CxuGuXXWnbDYuMGATMpFHtuiD8wgyAELmbAAgoWAMn6BBv04h5EkOxtLTWKvDcVwGKlhA6PyjNFLOpHqBRnApJ5FJC3bd23iZ5ZXuf62+3VxYCGn9guOZ5b0XwpcM30SfS1Tso1j4Sd4IA3TfUKhuQwPvRdA1ygzVNz3d2eh+A=
  - secure: Nu0K2y7fFuOxn5cy70+dBAgTA01XUjIJQJQC+Yq595/VHt8BttW2LJ1NL7KpxOTcROsRkqnMMU39PYbY6LUTE76W4zTyN6y0AVe/lsqUXhNtnSTsuziDRYNWi71JBcuox9kRcz48CUHgCBUJusY+VtIst/Y5xsnGCR1ZliIgjGHZKwAb58UfB+d7DatG5J3EDpDf3VRE5z/B0SHWsSO/lJYsNd1FZEOMqm2wn5Y/2ILds0M15h2RROrLylD/ykGohHRqdAJipHDOGt6VWiF9UDzYucIWXMqFuxIPkwXJQOomQWm2JqQcZPg3XZXeorwMhJmpZQrP7qwdkjWod6Y0RV5yZWMyq8NmoEIqqDlFtj8CTO9V9P5+/h8GGBugV2/tguW5+v4jrLfDwa3gjN2IuRxvDZ0Ks+ICwp3Hs5C2Y9eEoYBpya2G/5KqtdhHTwtnpPFQjRIV88miVzQeL3TxOUl6f4IS3NWhtJt2Ii2ws8qHKG5vtANKX8fKBfDnNkvSSW+Z4lqTPoCYF2Txa1AKRG+HERdK/b5STqFY3KEEqkukMbIjxY/2uFc+hyEocvZRRHJYGvRtOkwyn+OB8wWBKjLLb3DqxmpwniTPQsihpk2MtLiGGyp7fytgQe6OVDev3IHbC7VCL2TLxk8jXZHEVh+BAgqZxBno27nrChepEys=

cache:
  directories:
    - "~/.platformio"

install:
  - npm install
  - pip install -U platformio

jobs:
  include:
  - stage: test
    script: script/cibuild
  - stage: deploy
    if: type IN (pull_request)
    script: script/deploy
