sudo: required

dist: trusty

language: python

python:
  - '2.7'

node_js:
  - '6'

cache:
  directories:
    - "~/.platformio"
    - "~/node_modules"

before_install:
  - ls
  - cd platformio
  - ls

install:
  - ls
  # - npm install
  # - pip install -U platformio

# test
script:
  # - platformio/script/cibuild

# deploy
after_success:
  # - platformio/script/deploy
