sudo: required

dist: trusty

language: python

python:
  - '2.7'

node_js:
  - '6'

env:
  global:
  - secure: Sq5A2JFHgfjVqxp6GtQzbZAAV72Ikt/OMF2CCrrc8QsxuCxfPZ3KidTxuhRf1kHrjyQ/Ee0aQ0VQlJWB83Qw/kkVsILa+ZvxoD2ptewEHInEeAY4DF18jXOFXAEkwCfooLTSbw197BKBy3AWsM55J1ZDh1nE7m8D8YVVqEWpb+Tu7pcMkQVdNub40xD/xOghJcGC1djm4vxiQM/tpcA2RiW7pYrWT4WnJyF4XaJCwGltML8XhNcHb0qlV8KPaoivxF2szHf33oj2+mrkq8vG5dgHXAQTm5+N2bWrat4mMoVxRo5dyRbhG4gwclHGxaInlefls9MINDFhpx2iEdqIJivzsRon3TMy0nkvVYKY5Vcr4y483G64uo3qtKLoyjdQNCfZhhVtm5TPNmcHmRhuudW0wcrC53fZoq6v+EAHPS487ddojXvcvmcnUp0Y7pzA2bcNjya7maRnNBsjoM2txecWgwTpdIXFxNWQkI9PaFlzJTL6ePrHL8oKbcgVt/MsxQgODJiwKHCwiOjUWU1KbqQJZZZzcmZQw4kK9fmL7AVhJ2TPDHWFgw2KcHJeTa/mFQEMSgcq3JV+SPWkD1HcbQIphzJDuMY7Np5DwMaeQICTdIMKr+fjP+Ux9H2PmQ0VjbOaXdoLpRQMFKcpslBHpvXPXpt7vlqZgJUHqPL4JlA=
  - secure: bRJqIGo09xVlt9jxm05yeRBUe5krMRlJcDipnufIY6WyFY4Cq/bc5NROu+ZDhlWkWtic5wVkDdBU5FjQKwL75NMf0CXzokJ25Rv1YdIDH0+AlmnS8Ph3pAMahcggXMNoa1ADwTwxJEpBZoAzFLPh7Il5eE5yiSmDLWQPH2PrZwSnXybOGWDxwaODNvJ47ZkaztqIoGvcJuyFFbvmaXc8GF0jGC4UjVyilb5thL9ZsHdeITyWAiK+gtx6fBgRnTfvVOeNnflMcawSIKmbSNGn/tpqjWNKOiFHYD0uq0DwUO+9r3gcgpcOY5V3Juk05AmEsCIQzXe8FN1/ZhztdLiaY4dPwZ4nJELfu/58qLmKrjGxUl5mvjS8tmcgiXc8RHszJdwfmiH9UYL7dNjfY2MzV5t+BLFJVjRdhYo7EOKwWs0Cpy9GNks3EaSh58xLdL3JaYVEEWA7VpJfVVs4/8Oq197DLnnHV9W/5OrGm37SYWR55mkwl8wkY+kPVp8vakcsxWNJBRfqXeEWmDt9Sjov9JzgOHRRhm0eqiTwrfDVS4ZxieX/z45KJXzIbO8aOITzOEyNhVNTeqcQpOZI2LlRha5X+ucLlNNH1F6JrXbf17zJRA5Ii/awZpdFI+JZRg4Li+96AvrV/f9wxaCDtJSIYvkIJTC89wc76Qx6MdjNZmc=
  - secure: ps21aiurzfL0hFmmdIOvUYPNTEyVmAyRrpKIJGnkht946luL5kyqVv+avhpSTNl7mItQKngvEmi8TygVWIKKQi09af88Blj0tLNnW42rH8zxkumlxqRyxHVrzBTQSTctohQaV9JnFsaSngJuXFkgicfZtYUPirQ/YBj4v4mfbDVR32KC+XZCEA8lGAMDOVVf3bKAT5U170upS3ewOEFauT9IPTyNcHcYv8FAuYS2PBZnKAU+rlDHkuj9lAn7iUGqEegImfZwHieMR4SMkSFAmmhsHF/6Otk+m3bUGmW4oYLWkCFrWQBb9YVimMfcGZFO/3fYoK5JtG6w5uJOTPoDBMDqBWGLXibxdZ7Rp83ed3YEKxj1erzmCbR0P4q74T8yJOyRpw9TeEAwJ0HDvSKJvZf44YPSXB0nP2Gk0OvX9+Khzgy4TRZ58NHi4g57aA6isPPTBqdIRtW3e+qJb8L26XpgZQ1ZVw4FPAGJ8AdBCbt+Tx+k6td+PqABNLtzMxyvDV+Ac0IFuOUSBHhm2IILvLdER4Z00+Aj5DVO1MdbjhNHFoa2P/+r+4KZPRE2+laLFwGFmKkHGpwV8HHfWq5Nf2189MMAWzzTRofcJjMN/JVBS2TvooOwtoLqbfBw+nY38Em9VXMu3m3ux8Melby1fbwSCQYL9yPtaBXXvEbuSY8=
  - secure: IPZbC+xbMnKsuISAgMLBVXJDAjsQDSfFne1fdyOXQbEsahSXVHBL3p3VNdnZKK1SACFnjal+tlfmXwxQPhs7iaFJ7hrXCYNTXqVunHmVhuBqCpAcaU4dEco8Txf3OWb9TCyNDvBPfZsbbS4geI8+eU3/YQVgtnny4ovIUHSFf14PQIzasDM63yLFw2z6uUpYPRIVdpkTcR1zHQuCwrZ69a2P073TjGIIDwxubXt/xXZVugzshe5Z571Bm0Y7sg7iDv2w238cpQUepAJGYsZrz386YCBVS0CbNITwy0bR1TknBJpGXe2VKvZLI+7uI6yAgW7Fc4BA+Em+cr+48wZ1M2KLULt2+MovUl3mGdT6/7Kn1s9U0bUhGMyYbcthWLc4MbaBdCI3HZNuqd11D1g2MhsHcx3ZcNjW1asAMrRohkzqXX1BenzxX0Op9vOTQLk7zA8jbyV2G+l1lJjFGVXAYlncMsVqk+1ixngX5n7qGAK7hcqaNgCnYxIE9MEi97GO6WLheYWUKZfP2JmBYR7+zJ4Es68h/Lj+Ir9LKDWwIzpezWIyeiDW3djGQVZV+EeGWtslj9+Gq317b6XOVy2IFR3aFDd7J45txSyjyS6s8BzDSG5wWyqf2yvJH7x+87LxMmULoXK9trQTgXuV0WH6rb1DarK8BVwiPRQSGtw3YNs=
  - secure: SolF5cWPeror1q7TymVXfsKCp2qb3UxNIuYsIXXDh3y9I4c5FXNmGnFRdY0IVdBhThtbEfcF7tc8TDkaTDFLh6VPK1VNqesIjQmp91iw7SEqOQLQXmNhoEjKPMCwyLZznXnKgV36MoxR49lN4bT2nQ5KYiXC3pVOhEz5DSJCrjjhfDk13+Jh+qFSh3r8j9AeC9Xzj1WJ8x5AZ++Zwf24MZAmZzyImNRet5jW7OO+/SWdJxzGXQmGsxSzQ/1EoDv7r7z4YR7rAi+8BuQG08mO81P1rW911cBGOlmHTi3rY+qzsXPUBokUfvascagEBEHzOqCN1hgP9E11bOoPjsx/9F0BwK2oJmsV3mT7Aj3mVf6IOzgnHG2v736Os5wnxrh8VUfuZEHdzCOuxbQwO2DaWh/V1KIR5nbQvbO3YlmwJifJ3U9pQ7m0swyCqTiURuLE+qViib/5Kdjc2ePR/fy6qA4iZYr3KNfLF3YfYj4NmdtfXZN5QdMNewW/h7kPBsVB73Yl+9x3U1X8UMFqkQ18Kq2VmtIndj6qsSeB8V2Ik6mhpo46FXqD0igEILptgIsvTOuZ2oRGMPDwVq4GLwGcbL+yRyiNYVgEJEVss5vBvsdRcUuoxAYGQeCibLA7AcGonDIYK7VYYDE+9Y36pCr9ox2KgezvA+LGSWKhJIRrSWo=

cache:
  directories:
    - "~/.platformio"

install:
  - npm install
  - pip install -U platformio

jobs:
  include:
  - stage: test
    script: script/cibuild
  - stage: deploy
    if: type IN (pull_request)
    script: script/deploy
