sudo: required

dist: trusty

language: python

python:
  - '2.7'

node_js:
  - '6'

env:
  global:
  - secure: TG0C39NCfCzpdFd07y7FGx9wWIsLW4Whpyn1fg6HT2RctBsOv/N+P/V5xWRYH3F5A3ALfw4dUmNscuRU0ofnsQ9JklAjCZ+2Ctd+IDxL5nIzSkwniL0+cTsMI0VgSSMtkHcNBLYn0ArrxqoZY8VTxJSDEfiJXqtBRtF+BNG0hqRY1zV6HK2RCzJDDjfbFx37BRE6m3ZtLR6AScuxjevwS0adayu0V53LzUtAoI/kOxdZXAI+8EslXCx+BjYDWS8jjPL5/c8d0NlOZM29gfSRJqNZMyjLAokke7As2h82P8zaMJtS7HPy4wsHV0NomHICAsttJ75q2ipAGsGsbnm+qvpqDBN5I+nFbYD9KyCZl7BPmnmOgBKeLjvG8fCCEgft1u+Ipo+qOnoRcTlB2ftb9M25JVeRSUIpQXzkjAz5etLS5r5dv2jdVeGtVE0sdCGg5obq1SVK7rIQ44jhLQ5IgBQeb2tWFe9kA103UrUParC4w9C0qVXrAoL+wpD7v7gNnokKfeXIIhpfuckW56USXoXn/kgmqvXQ7UUFHJBTr+gnP/SnFGkECMrhuLOunEePR6LSB+6sjsEdpJPyTNb8NWpmWDh7NgH9lQe102tJ1OmMLfasE9LrbYPvhveeRDidhagFMrBrH3ByW0oM/96WYZoX0W8hjZ/XacR7atDX3s8=
  - secure: TQlgtEVpxtDvDOiOEkuwmUmqP4iThaofSE5OY9GxIaHAVasHLLyWOXotBMnhwijSH/eQxg7WsmjROngmeXq+SJkSOcnyYfyKrX/0vcfjljc+mea/Amm7zqwjWr5WRTHCp5N0KdEuApPnini0PFtrfqgEtN0aMM8WDWmWelj+7f9Kc18fxNv1G5DVR0pugpCM7D6VcASPSqJ1bTi/EDBY6cKINVBRvCqJ+Kip1VxuWheLZkMM/GW6qstr9WSEuoRqCOo47zSwiaYZNiLACHFrGvpAuKV+TJ20TAi/UQy3EVxjz37w3B7qH/t7VBF1tcCn9F0PeuN+1lvsvKQDwYZLCdhwToPjhugXCp+RhfUooACfKN+RSctmFvB31UMrZMn0DHOOSHROLOMT0C2tnp8ys/veLy7Lv92SNL19sHQlRbfEzRvqINKiNwt0CpCkg7Cu9DIZr16NLrsHqVhJqVmyUPKWGGX0E8k489GTo25kWAG9EP8XQ+5ecG8CxXhM4IVy+w/Y/IPCWplQLFh8KssCa7myetLNXDOuivjuKr+SNvAHwlT+2VTEmfkdEULXOCYhlJeUO/dCEOgo39yodHd4ezkYg2r+PUiaKdHeBoebwWLSEuomYQNXqNhqkiSjFYiRlVMlgXWEfEEOHD3Vh2vAMcdsEC6u4Nicbmwz2sjOxqo=
  - secure: cYDd1fmHjuV/APdfyPTjFVhvszQlZrqgUzV8aGZ4A+5I/Ok8RGB7xr695g0c3mtLHf1u79K/ucBLcN5N3MC9zQi5K2MRQYjASXhM5BRV2rRUfnfnDOsAzez8fPmPpiNkHWFg3xtMKky3XlonBsOHNyKe4RAAyk+x/qOWlXahB4vIS0IPiAPcHX8kCnXgTdqOY4Nq37Umje7AUnncgkoXlHVPzlXaBbSFmEdggMFhvbuKDJhUtqhBEJO53hFNpH/JDMFs0xllfVKpLx703+X8ALEmAmEZoNsrPgjK/rPskajiae83ELabdviCDDqgY2ixdcwsf/PT4x9I32Im/wDOmtOhwWMX2j2TqLafX7h7pfyMSc797Ve4QqQ2Gg5HHkEXaAdW+xn97qV3b1+i0hR4W5Gjx8Sx3oJyUXC3lYCUwmRiwWaFkLuKUUJ1K+uRWIPUEeuK3culZtZ7hdEA6K2YxD9DZuak5psMbMWSMukVosoCzO97L9YtlDTZhT7hfpVmgPb9pq/okz/wLxm7NQoRPxwYw3bCzCQq23s3PEgTeZ9WyF/Zuxj41s1CCFJeh/TKAjuRdKtq1grvROWblCELmdHd8Ytyktm54TNc9Z9IegpvzvJ5SG7Suj7wdv3q3tSkX/JcUawAV7vxXe26RzH5Nd+9C/ckfh5XonbIqM/96fw=
  - secure: M2z7ehMduFmtdzQdIXtNgto1A2aAMNJJF/r2l6SY4tzzZtbpj35boCcGk+/CgQBr0rmkN2It7C+Oqy9fiv/GrIM96SVv/ZqUxXaHuPrOCsarZOg3NE6etlSgdH4GqX75wShxjOfCZJRDj59MXsXihKF3if8qt4K/oJys4RS8eF5Jo21QenvwlOEI/vpcIg4cHCuzJNlRGwe6klpNrc1MpJutLBJxlZJ2nRyAcbkBuQus11SChAO7+81ckRwD68CEBK9xYshwLDZzSCqEjEA3gskODtugoVuncL2T69cqu0Troyyi8W4CKDkaYlv+fC4HV2fmve1pfVhvDq6/kh3I+oABW4KRNHoTHACEMcxgLapZdwDMo9kRxLav4ZivXLEtkG5ly9rQCTrfxhCbygNSK/Efb7TbGUU4PJZIo05a5lECrcgXKGPLK/9K+MdnTszg73CeuXx0HWtPd2PAyyJl7nDkRMqCt12nz0DLSWQTAMYaY2EZaqhBrq8ZohdNfNhk4RbfMqxV/WsnOSS7p3ign6tUp9c2hWEAbeOqcQ6fTSmkTb8/R+5fQQQB0l2HSwCEFCj1CUN1ZhjJTpnk14l3g0P5pZVkhR8a6HmJLy+DeYaX3sAsdvH0yKocPhiIBtdIxHmleEGkr4dfENS0DhrySF2bl4KClMDaP1DaSUzKphg=
  - secure: LB/L0fC8Zmm0etSJGnjmYZTxAYZyhEV99wXlFWQjSCX/DRZ/e+4XXQ7iPmH0bsFXaMijcBu+lvSjFpOt7uegki/gun4FqYJ7Qq9fL5IuMtDFSBkrMpcmjvzwArd7vPjUYgXX55/QvsmaL0UpPuOJY3vu1ikuadt/0kWE3APEq9BdhQrxkxN58Z2gBN/Qd1TiEKEr/k7s5VRb3ImNq+NPmI7zqj03DQnbNG0qGavV+MWCBCT/QH10UuuIbRkPSAxQ/a/uzvaVUDEGO6KdGOMFodvT0tdtIzAPpr3WEl1EJZgSlWULE+/xOi3i1bY4ENzjHXO9zM60af+VwpUxAhQCyWgTxkzkec1ZG3S51oJDaQnEM4/J3YEoCnNMPRG9TcF4Basjtl0g+v+cLvPpD3HoP4A5mTqa34Hz5FMLxBBmjvzMTTluBkIi7IpCh3k0+ApgjZ0HL3oO/x9nP5606iiV0msvEdE7bxF6RqskbIdkXTKEssabnTErqdNORt2j0hfm9xgioWAUTnSvgOFz9FwM8swQTrPUJnOgGJAfXOy4yIgku0WbaWOUjiFH0VLHCp6QavzCaUedL2N2uE4Ak0hZDn/XZ+a5WGetvmwhm3JxTy7OPJBpXsiVPmKlrv46ITElC2gV6lKKjkCVwc4heJnIlvZfMdYpXUA2xHGH721j3pE=

cache:
  directories:
    - "~/.platformio"

install:
  - npm install
  - pip install -U platformio

# test
script:
  - script/cibuild

# deploy
after_success:
  - 'script/deploy'
