version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: circleci/node:7

    working_directory: ./platformio

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "platformio" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            npm install
            pip install -U platformio

      - save_cache:
          paths:
            - node_modules
            - .platformio
          key: v1-dependencies-{{ checksum "platformio" }}
