version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: circleci/node:7

    steps:
      - checkout

      - run:
          name: run
          command: |
            echo ":wave:"
